name: acme-donations

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  api-php:
    profiles: ["dev", "prod"]
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
      - CACHE_STORE=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=database
      - DB_CONNECTION=sqlite
      - SANCTUM_STATEFUL_DOMAINS=localhost:5173,localhost,127.0.0.1,web,host.docker.internal
      - SESSION_SECURE_COOKIE=false
      - SESSION_SAME_SITE=lax
      - SESSION_DOMAIN=
      - APP_KEY=base64:YJgmtLJEpaemj5Z8QuK0OxXQ4bwzakaq5dqganLW8BM=
      - APP_NAME=ACME Donations
      - APP_URL=http://localhost:8080
      - REDIS_HOST=redis
      - COMPOSER_CACHE_DIR=/tmp/composer-cache
    volumes:
      - ./api:/var/www/html
      - api_storage:/var/www/html/storage
      - api_vendor:/var/www/html/vendor
      - composer_cache:/tmp/composer-cache
    depends_on:
      redis:
        condition: service_healthy

  api-nginx:
    profiles: ["dev", "prod"]
    image: nginx:alpine
    depends_on:
      - api-php
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html:ro
      - api_storage:/var/www/html/storage
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  queue-worker:
    profiles: ["dev", "prod"]
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
      - CACHE_STORE=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=database
      - DB_CONNECTION=sqlite
      - SANCTUM_STATEFUL_DOMAINS=localhost:5173,localhost,127.0.0.1,web,host.docker.internal
      - SESSION_SECURE_COOKIE=false
      - SESSION_SAME_SITE=lax
      - SESSION_DOMAIN=
      - APP_KEY=base64:YJgmtLJEpaemj5Z8QuK0OxXQ4bwzakaq5dqganLW8BM=
      - APP_NAME=ACME Donations
      - APP_URL=http://localhost:8080
      - REDIS_HOST=redis
      - COMPOSER_CACHE_DIR=/tmp/composer-cache
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh", "-lc", "php artisan queue:work --queue=default,donations,notifications,cache --tries=3 --backoff=5"]
    volumes:
      - ./api:/var/www/html
      - api_storage:/var/www/html/storage
      - api_vendor:/var/www/html/vendor
      - composer_cache:/tmp/composer-cache

  web:
    profiles: ["dev"]
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - api-nginx
    volumes:
      - ./web:/app
      - ./shared:/app/shared:ro
      - /app/node_modules

  web-static:
    profiles: ["prod"]
    image: nginx:alpine
    depends_on:
      - api-nginx
    ports:
      - "5173:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  api_storage:
  api_vendor:
  composer_cache:


